### ISSUE TITLE
Touchy takes over events (or so I think)

### ISSUE THREAD

**Issue by Drvanon** [HotStudio/touchy#12]
When I use touchy-pinch, I can't use jquery's (or phonegap's) touch-start event.

**Comment by fisherwebdev** [comment]
To answer your question effectively, I probably need to see how you are using Touchy.  Can you post some code?

Or try this, but without more context I'm not sure if it will work for you: 

``` javascript
$('#my_div').data('touchyPinch').settings.preventDefault.start = false;
```

The default of the above configuration setting is true, which pretty much stops touchstart in its tracks.  However, if you change this setting to false, you will now see the mousedown and click events fire, which you might not want.  Preventing these events from firing is the reason why Touchy calls event.preventDefault().

Also note that Touchy is based on its own event delegation scheme, and this can be limiting if you are trying to set up an event delegation of your own.  You can try overriding that setting, but it is computationally expensive and may not work exactly as you expect.  For more discussion of that issue, see issues #4 and #5.

``` javascript
$.touchyOptions.useDelegation = true;
```
