### ISSUE TITLE
Pinch and Drag within the same element

### ISSUE THREAD

**Issue by omsoft** [HotStudio/touchy#13]
Is it possible to apply 2 different events to the same element of the page?
I'd like to pinch-zoom an image and drag it at the same time, for reading purposes inside a jQuerymobile application.

Thanks

**Comment by fisherwebdev** [comment]
Yes touchy-pinch and touchy-drag may be used at the same time.  You will need to bind each event separately, however.

Also, here is a video of of a talk, given by Flickr's Stephen Woods, about how you might approach that same task with native code:
http://www.youtube.com/watch?v=lcD9CF0bxyk
