### ISSUE TITLE
touch-swipe - Triggered only once

### ISSUE THREAD

**Issue by simonwalsh** [HotStudio/touchy#15]
I cannot understand why touch-swipe is triggered only once ? I'm building a wepapp that acts like a book and would love to be able to re-swipe pages. I tried re-binding the event in the handler, to no avail.

Any thoughts ? I really don't master the JS events so I might be just not understanding how to reuse them properly...

Thanks! Simon

**Comment by fisherwebdev** [comment]
Please see the demo: http://hotstudio.github.io/touchy/examples/drag-and-flick.html

Another test page for this is located at https://github.com/HotStudio/touchy/blob/master/test-pages/swipe.html

Your code should be as simple as:

```
$("#swipe_area").on("touchy-swipe", handleTouchySwipe);
```

...and handleTouchySwipe contains all the code you need to perform your animation.  If you are still having trouble, take a look at your Touchy settings.  These may be tweaked with code like this example:

```
$swipeArea.data("touchySwipe").settings.velocityThresh = 0.3;
```

Also, you may want to provide me with a link to your code, so I can help you further.
