### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by Paul-Isache** [HotStudio/touchy#17]
Can I be made to work on click ?
I have searched on the internet and this is by far the best rotate and i tried by my self to make it work for on click but i failed.
Can you please help me ?
Thank you

**Comment by fisherwebdev** [comment]
Click has a ~300ms delay on mobile devices.  Touchy is based on touchstart, touchmove and touchend.  It will not support click, and in general you should probably not use click for touch screens.  Click is provided to touch screens by the browsers as a somewhat lame fallback.
