### ISSUE TITLE
Touchy.js doesn't work with jQuery 1.5.2 

### ISSUE THREAD

**Issue by voronianski** [HotStudio/touchy#3]
It is mentioned that plugin works with jQuery 1.4.2 and upper versions but it's false, it get worked only from 1.6
Please, help me with integration of 1.5.2

**Comment by fisherwebdev** [comment]
fixed this bug.  please get the latest update.

please see these test pages:
http://hotstudio.github.com/touchy/test-pages/swipe-1-5-2.html
aliased at: http://goo.gl/u3tr2
http://hotstudio.github.com/touchy/test-pages/swipe-1-4-2.html
aliased at: http://goo.gl/j4rE8

thanks very much for raising this issue!
