### ISSUE TITLE
preventDefault should be optional

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [HotStudio/touchy#6]
I had a case in which I did not want preventDefault() to be called on touchstart, etc. (I wanted to be able to swipe and use normal scrolling).
The only way to do this at the moment is to comment out the lines in the touchy lib.

Would it be possible to configure the use of preventDefault() using a setting?

Thanks

**Comment by fisherwebdev** [comment]
I added this.  Thanks for the suggestion, and my apologies for not being able to get to this sooner.  You can now disable preventDefault within each phase: start, move or end.  Please see the settings code at the beginning of the file.  Any feedback is most welcome.

**Comment by Joris-van-der-Wel** [comment]
Thank you, looks like it is working great.
