### ISSUE TITLE
Rotate doesn't seem to work in latest version of Chrome on Android

### ISSUE THREAD

**Issue by Apophenian** [HotStudio/touchy#7]
Version 26.0.1410.58  doesn't seem to support rotate any more (definitely was working about 2 weeks ago) - can test with wheel demo on touchy's home page.

Thanks,

Rane

**Comment by fisherwebdev** [comment]
The rotate3d syntax was off.  Apparently, old Chrome was compensating for my bad syntax.  I fixed the syntax for the examples.

**Comment by fisherwebdev** [comment]
Also updated the gh-pages branch so you should be able to see this working at the following:
http://hotstudio.github.io/touchy/examples/wheel.html
http://hotstudio.github.io/touchy/examples/wheel-inertia.html

**Comment by Apophenian** [comment]
Excellent, thanks!
